name: PR Pipeline

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
      - '*.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: devel-cache-${{ runner.os }}-gradle-v1-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew spotlessCheck lintDebug --stacktrace

      - name: Run unit tests
        run: ./gradlew check --stacktrace

      - name: Bundle build reports
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: error-report
          path: build-reports.zip

      - name: Generate android app bundle
        run: ./gradlew bundle

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            app/build/outputs/bundle/debug/app-debug.aab
            app/build/outputs/bundle/debug/app-release.aab
