name: PR Pipeline

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
      - '*.yml'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: java --version

      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - run: chmod +x gradlew

      - name: Run ktlint check
        run: ./gradlew ktlintCheck

      - name: Run tests
        run: ./gradlew check --stacktrace

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip

#      - name: Build Android App Bundle (.aab)
#        run: ./gradlew bundle
#
#      - name: Upload AAB Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: app-bundle
#          path: app/build/outputs/bundle/**/*.aab
